### ISSUE TITLE
De Imagen en formato JPG a K'iche

### ISSUE THREAD

**Issue by garfenter** [jgranadosiastic/Koky#27]
¡Hola! Agregue una pequeña funcionalidad que convierte una imagen .JPG en código Koky en lenguaje K'iche

![image](https://user-images.githubusercontent.com/4163099/77131186-5bced200-6a20-11ea-8093-364f8c78aa35.png)

Esto es para un video de YouTube que estoy trabajando en el cuál hablaré de su herramienta. Me encantó, esta muy bonita y tiende código muy comprensible. 

Me preguntaba si te interesa agregarlo a la rama principal.

Saludos

**Comment by jgranadosiastic** [comment]
Hola, gusto en conocerte. Me parece una funcionalidad bastante interesante. 
Por lo que entiendo, esa funcionalidad consiste en que Koky lea un archivo JPG y a partir de esa data se genera el codigo en k'iche' para que se pueda dibujar dicha imagen por medio de Koky?

**Comment by garfenter** [comment]
Si, así es.  La pixelea y genera el código para generar la imagen. Podría crear un pull request para que veas los cambios realizados.

**Comment by garfenter** [comment]
Solamente necesitaría acceso para crear el branch :$

**Comment by jgranadosiastic** [comment]
Claro, te agrego como colaborador para crear la rama

**Comment by garfenter** [comment]
¡Hola Jose! Termine el vídeo que estaba haciendo sobre Koky, espero te guste: 

En FB
 https://www.facebook.com/iPilasPues/videos/684442488994918/
En YouTube 
https://youtu.be/wzgPCnYnfAQ

Espero sea de tu agrado. Cualquier comentario no dudes en hacérmelo llegar.
